Feature/user profile
shilangyu/SE2-CBT pull request #179
Opened 2022-04-26 14:47 UTC by wolftender

closes #178 

in this episode of endless uphill struggle with the spec:

- user profile works
- password changing is not in the endpoint thus i assume it is not required to work on the frontend
- changing email causes token to not identify the user anymore but since it is implemented in the backend it can be done from the frontend
- updated the `PUT /user/{id}` (where id is email for some reason) endpoint to accept partial changes so we dont have to change `banned` status every time we need to change something else

2022-04-26 21:32 UTC, Zaczero approved these changes

2022-04-27 10:47 UTC, shilangyu requested changes
It would also be beneficial to split ProfilePage into few components (which will make it much easier to test).

2022-04-27 11:21 UTC, wolftender commented on web/src/utils/jwt.ts
> +    const claimsBuffer = Buffer.from(tokenParts[1], 'base64')
https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_.22unicode_problem.22

its a lot easier to just not worry about it

2022-04-27 11:54 UTC, wolftender commented
> It would also be beneficial to split ProfilePage into few components (which will make it much easier to test).

we can do that later if it is needed, one thing we could make is somehow merge `useRegisterForm` and `useUserEditorForm` but this is not a crucial feature

2022-04-27 12:22 UTC, shilangyu approved these changes

2022-04-27 12:24 UTC, merged